import type { TemplateDefinition } from "@/templates/types"

export const definition: TemplateDefinition = {
  kind: "modern-minimalist",
  name: "Modern Minimalist",
  category: "Modern",
  occasions: ["pernikahan"],
  description:
    "Clean whitespace, large editorial typography, asymmetric sections and a restrained palette. Built for the modern urban wedding.",
  tags: ["Modern", "Minimal", "Editorial"],
  thumbnail:
    "https://images.unsplash.com/photo-1519741497674-9b181a268d28?auto=format&fit=crop&w=800&q=60",
  theme: {
    primary: "#1f2937",
    secondary: "#111827",
    background: "#ffffff",
    surface: "#f7f7f5",
    text: "#1f2937",
    muted: "#6b7280",
    accent: "#9ca3af",
    border: "#e5e7eb",
    radius: "0.5rem",
    fontHeading: "'Playfair Display', serif",
    fontBody: "'Inter', sans-serif",
    fontAccent: "'Playfair Display', serif",
    sectionSpacing: "5rem",
    contentWidth: "64rem",
    heroHeight: "92vh",
    animationDuration: "0.7s",
    animationEasing: "cubic-bezier(0.22,1,0.36,1)",
    revealDistance: "36px",
  },
  night: {
    primary: "#d1d5db",
    secondary: "#9ca3af",
    background: "#111827",
    surface: "#1f2937",
    text: "#e5e7eb",
    muted: "#9ca3af",
    accent: "#6b7280",
    border: "#374151",
  },
  nav: "bottom-floating",
  animation: { variant: "fade-up", stagger: true, parallax: false },
  decoration: "none",
  timelineStyle: "minimal",
  sections: [
    { key: "cover", variant: "minimal" },
    { key: "quote" },
    { key: "couple", variant: "portrait" },
    { key: "events", variant: "cards" },
    { key: "add-to-calendar" },
    { key: "gallery", variant: "grid" },
    { key: "love-story", variant: "minimal" },
    { key: "rsvp" },
    { key: "gift" },
    { key: "guestbook" },
    { key: "closing" },
  ],
}

export default definition
